# Generated by Django 3.0.1 on 2019-12-21 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('post_date', models.DateTimeField(default=datetime.datetime(2019, 12, 20, 22, 17, 2, 797628), unique=True)),
                ('path', models.ImageField(upload_to='ComicCozy/comics/', verbose_name='Image filepath')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('text', models.TextField(blank=True, verbose_name='Post text')),
            ],
            options={
                'get_latest_by': 'post_date',
            },
        ),
    ]
