# Generated by Django 3.0 on 2019-12-06 04:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComicCozy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comic',
            options={'get_latest_by': 'post_date'},
        ),
        migrations.AlterField(
            model_name='comic',
            name='path',
            field=models.ImageField(upload_to='ComicCozy/', verbose_name='Image filepath'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 5, 20, 5, 16, 206651), unique=True),
        ),
    ]
