# Generated by Django 3.0.1 on 2019-12-21 06:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_auto_20181220_0803'),
        ('ComicCozy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationBarSetting',
            fields=[
                ('preferences_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='preferences.Preferences')),
                ('first_button_text', models.CharField(default='<<', max_length=200)),
                ('first_button_image', models.ImageField(blank=True, help_text='Leave blank to use the text above instead', upload_to='ComicCozy/resources/')),
                ('previous_button_text', models.CharField(default='<', max_length=200)),
                ('previous_button_image', models.ImageField(blank=True, help_text='Leave blank to use the text above instead', upload_to='ComicCozy/resources/')),
                ('next_button_text', models.CharField(default='>', max_length=200)),
                ('next_button_image', models.ImageField(blank=True, help_text='Leave blank to use the text above instead', upload_to='ComicCozy/resources/')),
                ('last_button_text', models.CharField(default='>>', max_length=200)),
                ('last_button_image', models.ImageField(blank=True, help_text='Leave blank to use the text above instead', upload_to='ComicCozy/resources/')),
            ],
            bases=('preferences.preferences',),
            managers=[
                ('singleton', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='comic',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 20, 22, 18, 21, 837954), unique=True),
        ),
    ]
